env:
  node: true
  browser: true
  commonjs: true
  es2020: true
  mocha: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 11
rules:
  quotes: ["warn", "single", "avoid-escape"]
  indent: ["error", 4]